# BASE UI
ColorColumn: ''
Conceal: ''
Cursor: ''
CursorIM: ''
CursorColumn: ''
CursorLine: '- cursorline'
CursorLineNR: 'cursorlinenumber'
Directory: ''
DiffAdd: ''
DiffChange: ''
DiffDelete: ''
DiffText: ''
ErrorMsg: ''
VertSplit: 'linenumber bg'
Folded: ''
FoldColumn: ''
SignColumn: ''
IncSearch: ''
LineNr: 'linenumber'
MatchParen: ''
ModeMsg: ''
MoreMsg: ''

# these are the tildes at the end which I've opted
# to make disappear, but may not be preferred
NonText: 'bg'

Normal: 'fg bg'
PMenu: ''
PMenuSel: ''
PmenuSbar: ''
PmenuThumb: ''
Question: ''
Search: '- search'
SpecialKey: ''
SpellBad: ''
SpellLocal: ''
SpellCap: ''
SpellRare: ''
StatusLine: ''
StatusLineNC: ''
TabLine: ''
TabLineFill: ''
TabLineSel: ''
Title: ''
Visual: '- highlight'
VisualNOS: ''
WarningMsg: ''
WildMenu: ''

# BASE SYNTAX
Comment: 'comment'
Constant: 'orange'
String: 'string' # Constant
Character: '' # Constant
Boolean: 'orange' # Constant
Number: 'orange' # Constant
Float: '' # Constant
Identifier: ''
Function: 'yellow' # Identifier
Statement: ''
Conditional: 'blue' # Statement
Repeat: 'blue' # Statement
Label: '' # Statement
Operator: 'lightgray' # Statement
Keyword: '' # Statement
Exception: '' # Statement
PreProc: ''
Include: '' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: ''
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: ''
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: ''
Ignore: ''
Error: ''
Todo: ''

# JavaScript
jsArrowFunction: 'fg'
jsArrowFuncArgs: 'lightblue'
jsBooleanFalse: 'orange'
jsBooleanTrue: 'orange'
jsBraces: 'lightgray'
jsCatch: 'blue'
jsComment: 'comment'
jsExport: 'blue'
jsFrom: 'blue'
jsFuncArgs: 'lightblue'
jsFuncBraces: 'lightgray'
jsFuncCall: 'yellow'
jsFuncName: 'yellow'
jsFuncParens: 'lightgray'
jsFunction: 'teal'
jsGlobalObjects: 'yellow'
jsImport: 'blue'
jsModuleAs: 'blue'
jsModuleAsterisk: 'orange'
jsModuleBraces: 'lightgray'
jsNull: 'orange'
jsNoise: 'lightgray'
jsNumber: 'orange'
jsObjectBraces: 'lightgray'
jsObjectColon: 'lightgray'
jsObjectProp: 'blue'
jsObjectSeparator: 'lightgray'
jsObjectValue: 'lightblue'
jsOperator: 'lightgray'
jsParens: 'lightgray'
jsReturn: 'blue'
jsStorageClass: 'teal'
jsTemplateBraces: 'pink'
jsTry: 'blue'
jsUndefined: 'orange'
jsExportDefault: 'blue'
jsGlobalNodeObjects: 'blue'
jsException: 'blue'
jsExceptions: 'yellow'
jsRepeat: 'blue'

# JSON
jsonBoolean: 'burntorange'
jsonBraces: 'fg'
jsonKeyword: 'lightblue'
jsonFold: 'fg'
jsonNoise: 'fg'
jsonString: 'string'

# YAML
yamlBlockMappingKey: 'lightblue'
yamlKeyValueDelimiter: 'fg'
# jsonKeywordMatch: 'string'
# jsonQuote: 'lightblue'

# XML/React/HTML
xmlAttrib: 'lightblue'
xmlEndTag: 'yellow'
xmlEqual: 'lightgray'
xmlTag: 'lightgray'
xmlTagName: 'yellow'

# vim
vimAddress: 'pink'
vimAutoCmd: 'blue'
vimAutoEvent: 'lightblue'
vimBracket: 'pink'
vimCommand: 'blue'
vimCommentTitle: 'lightgray'
vimContinue: 'lightgray'
vimFgBgAttrib: 'fg'
vimHiCtermFgBg: 'lightblue'
vimHiGroup: 'lightblue'
vimHiGuiFgBg: 'lightblue'
vimHiKeyList: 'lightblue'
vimLet: 'teal'
vimMap: 'blue'
vimMapMod: 'pink'
vimMapModKey: 'pink'
vimNotation: 'pink'
vimNumber: 'orange'
vimOperParen: 'lightgray'
vimOption: 'lightblue'
vimParenSep: 'lightgray'
vimSep: 'lightgray'
vimSetSep: 'lightgray'
vimSubst1: 'lightblue'
vimSubstDelim: 'pink'
vimSubstFlags: 'pink'
vimUserFunc: 'yellow'
vimVar: 'fg'

# groovy
groovyJDKBuiltin: 'teal'
groovyParen: 'lightgray'
groovyType: 'blue'
groovyStatement: 'blue'
groovyNumber: 'orange'
groovyBoolean: 'orange'
groovyELExpr: 'pink'
groovySpecialChar: 'orange'
groovyExceptions: 'blue'
groovyUserLabel: 'lightblue'

# markdown
markdownBlockquote: 'lightblue'
markdownBold: 'lightblue - ib'
markdownBoldDelimiter: 'lightgray'
markdownCodeDelimiter: 'pink'
markdownH1: 'fg - b'
markdownH2: 'fg - b'
markdownH3: 'fg - b'
markdownH4: 'fg - b'
markdownH5: 'fg - b'
markdownH6: 'fg - b'
markdownHeadingDelimiter: 'lightgray - b'
markdownHeadingRule: 'lightgray'
markdownId: 'teal'
markdownIdDeclaration: 'teal'
markdownItalic: 'lightblue - i'
markdownItalicDelimiter: 'lightgray'
markdownLinkText: 'string'
markdownListMarker: 'lightgray'
markdownOrderedListMarker: 'lightgray'
markdownUrl: 'blue'
markdownUrlDelimiter: 'lightgray'
markdownUrlTitleDelimiter: 'lightgray'



